language : java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


branches:
  master:
    script:
      - jdk_switcher use oraclejdk8
      - ./gradlew travisbuild
  develop:
    script:
      - echo $PATH

#before_script: .travis/setup.sh
#script: .travis/build.sh

script:
  - jdk_switcher use oraclejdk8
  - ./gradlew check test


